import { createClient } from '@supabase/supabase-js'

// Environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

// Client-side Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Server-side Supabase client (for API routes - uses service role)
export const createServerSupabaseClient = () => {
  return createClient(supabaseUrl, supabaseServiceKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  })
}

// Browser-safe client for client components
export const createBrowserSupabaseClient = () => {
  return createClient(supabaseUrl, supabaseAnonKey)
}

// Database types (auto-generated by Supabase)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          password_hash: string | null
          image: string | null
          role: string
          account_type: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          password_hash?: string | null
          image?: string | null
          role?: string
          account_type?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          password_hash?: string | null
          image?: string | null
          role?: string
          account_type?: string
          created_at?: string
          updated_at?: string
        }
      }
      carbon_activities: {
        Row: {
          id: string
          user_id: string
          type: string
          category: string
          amount: number
          description: string
          location: any | null
          metadata: any | null
          timestamp: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          category: string
          amount: number
          description: string
          location?: any | null
          metadata?: any | null
          timestamp: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          category?: string
          amount?: number
          description?: string
          location?: any | null
          metadata?: any | null
          timestamp?: string
          created_at?: string
          updated_at?: string
        }
      }
      goals: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          target: number
          current: number
          unit: string
          period: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          target: number
          current?: number
          unit?: string
          period: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          target?: number
          current?: number
          unit?: string
          period?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      achievements: {
        Row: {
          id: string
          user_id: string
          type: string
          name: string
          description: string | null
          achieved_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          name: string
          description?: string | null
          achieved_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          name?: string
          description?: string | null
          achieved_at?: string
        }
      }
    }
  }
} 